language: python

sudo: false

python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'

os:
  - linux

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - py.test
  - flake8
  # Ensure latest pytest-attrib in pypi works
  - pip uninstall pytest-attrib -y
  - python setup.py sdist
  - pip install --no-deps --no-cache-dir --force-reinstall --no-index --find-links dist pytest-attrib

notifications:
  email: false
